name: pinwheel
description: A flutter plugin for the Pinwheel Link SDK.
version: 0.0.2
homepage: https://github.com/underdog-tech/pinwheel-flutter-sdk
documentation: https://github.com/underdog-tech/pinwheel-flutter-sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^8.0.6

flutter:
  plugin:
    platforms:
      android:
        package: com.getpinwheel.pinwheel
        pluginClass: PinwheelPlugin
      ios:
        pluginClass: PinwheelPlugin
